var path=require("path"),Promise=require("bluebird"),inq=require("inquirer"),log=require("npmlog"),Table=require("easy-table"),fs=Promise.promisifyAll(require("fs-extra")),readJsonSync=require("./util/json").readJsonSync,readJsonAsync=require("./util/json").readJsonAsync,copyToDirAsync=require("./util/copy").copyToDirAsync,merge=require("./util/merge"),Git=require("./util/git"),git=new Git;
function Generator(f){function k(a){if(a){var f=path.join(__dirname,"..");a=fs.readFileSync(a);a=a.toString().replace(/\$cli-root/gi,f).replace(/\\/g,"/");d=JSON.parse(a)}else d=null}var d;k(f);this.setTmplates=k;this.getTemplates=function(){return d}}
Generator.prototype.showTemplates=function(f,k){var d=this.getTemplates(),a=new Table,l={webapp:"Web App",nativeapp:"Native App",webappinfo:"Web App Info",nativeappinfo:"Native App Info",jsservice:"JS Service",nativeservice:"Native Service",jsserviceinfo:"JS Service Info",nativeserviceinfo:"Native Service Info",icon:"Icon",library:"Library"},b;for(b in d)if(!0!==d[b].hide&&d[b].type){var p=d[b]["default"]?"(default) ":"",q=d[b].branch||"-",r=l[d[b].type]||d[b].type;k&&-1===["true","false",!0,!1].indexOf(k)&&
d[b].type&&null===d[b].type.match(new RegExp(k+"$","gi"))||(a.cell("ID",b),a.cell("Project Type",r),a.cell("Version",q),a.cell("Description",p+d[b].description),a.newRow())}console.log(a.print())};
Generator.prototype.generate=function(f){function k(b,c,a){log.verbose("Generator.generate()._writeMetadata()");var m=[].concat(b.path);c=c||{};a=a||{};return Promise.all(m.map(function(m){return fs.lstatAsync(m).then(function(e){if(!e.isFile())throw e="Invalid metadata template path:"+m,log.warn("Geneator.generate()._writeMetadata()#warn","Invalid metadata template path:"+m),Error(e);e=readJsonSync(m);var t=path.basename(m);"appinfo.json"===t?e=merge(e,c):"services.json"===t?e=merge(e,a):"package.json"!==
t||"jsserviceinfo"!==b.type&&"nativeserviceinfo"!==b.type||(e.name=a.id||e.name);return e}).then(function(c){var a=path.join(n,path.basename(m));return fs.mkdirsAsync(n).then(function(){return fs.writeFileAsync(a,JSON.stringify(c,null,2),{encoding:"utf8"})})})})).then(function(c){log.verbose("Geneator.generate()._writeMetadata() done.")})["catch"](function(c){log.verbose("Geneator.generate()._writeMetadata()#err:",c);throw c;})}function d(a,c,b,e){var m=[],d;for(d in a.sources)m.push({url:a.sources[d],
target:b||a.targets[d],locate:a.locates?path.join(c,a.locates[d]):path.join(c,"lib")});return Promise.all(m.map(function(a){try{fs.accessSync(a.locate,fs.F_OK);if(!e)throw Error(a.locate+' exits. Please set "overwrite".');log.verbose("_downloadLibs()#Removing an existing directory at ",a.locate);return fs.removeAsync(a.locate).then(function(){return git.shallowClone(a.url,a.locate,a.target)})}catch(u){if(u&&"ENOENT"===u.code)return log.verbose("_downloadLibs()",a.locate+" does not exists. start git shallow clone."),
git.shallowClone(a.url,a.locate,a.target)}})).then(function(c){log.verbose("_downloadLibs() done.");return a})["catch"](function(a){log.verbose("_downloadLibs()#err:",a);throw a;})}var a=f.tmplName,l=f.appinfo,b=f.svcName,p=!!f.overwrite,q=!!f.query,r=f.out,e,g=this.getTemplates(),n=path.resolve(r),h=g[a];if(!h||"requireCommands"===a)return Promise.reject(Error("Invalid template name"));h.metadata&&h.metadata.data&&"object"===typeof h.metadata.data&&(l=merge(l,h.metadata.data));b&&(e={},e.id=b,e.services=
[{name:b}]);return Promise.resolve().then(function(){if(g.requireCommands&&-1!==g.requireCommands.indexOf("git"))return git.verifyGit({openUrl:!0})}).then(function(){try{var a=fs.readdirSync(n);return inq.prompt([{type:"confirm",name:"overwrite",message:"The directory already exists, overwrite?","default":!1,when:function(c){return!p&&q&&0<a.length}}]).then(function(c){f.overwrite=c.overwrite||f.overwrite;if(0<a.length&&!f.overwrite)throw Error(n+" is not empty. Please check the directory.");})}catch(c){if(c&&
"ENOTDIR"===c.code)throw Error(n+" is not a directory. Please check the directory path.");if(c&&"ENOENT"===c.code)log.verbose("Generator.generate()","The directory does not exist.");else throw c;}}).then(function(){log.verbose("Generator.generate()","template name:"+a);console.log("Generating "+a+" in "+n);if(h.type.match(/info$/))return k(h,l,e);var b=[].concat(h.path);return Promise.all(b.map(function(a){log.verbose("Generator.generate()","template src:"+a);return copyToDirAsync(a,n)})).then(function(){var a;
h.metadata&&h.metadata.id&&(a=g[h.metadata.id]);if(a)return k(a,l,e)})}).then(function(){return Promise.all((g[a].deps||[]).map(function(a){if(g[a]){if(g[a].path)return copyToDirAsync(g[a].path,n);log.warn("Generator.generate()","Invalid template path "+a)}else log.warn("Generator.generate()","Invalid template id "+a)}))}).then(function(){if(!h.type.match(/info$/)&&!h.type.match(/icon$/)){log.verbose("Generator.generate()","target branch is "+g[a].branch);var b;b=path.join(n,".enyoconfig");try{return fs.accessSync(b,
fs.F_OK),readJsonAsync(b).then(function(b){return d(b,n,g[a].branch,f.overwrite)}).then(function(e){if(e&&e.targets){for(var c in e.targets)e.targets[c]!==g[a].branch&&(e.targets[c]=g[a].branch);return fs.writeFileAsync(b,JSON.stringify(e,null,2))}})}catch(c){if(c&&"ENOENT"===c.code)log.verbose("Generator.generate()",b+" does not exist.");else throw c;}}}).then(function(){log.verbose("Generator.generate() done.");return{msg:"Success"}})["catch"](function(a){log.verbose("Generator.generate()#err:",
a);throw a;})};
Generator.prototype.init=function(f){function k(a,d){var b=[];log.verbose("Generator.init()._checkoutLibs()");for(var f in a.sources)b.push({url:a.sources[f],target:a.targets[f],locate:a.locates?path.join(d,a.locates[f]):path.join(d,"lib")});return Promise.all(b.map(function(a){try{return fs.accessSync(a.locate),git.unshallowRepo(a.locate).then(function(){return git.checkoutRepo(a.locate,a.target)})}catch(g){if(g&&"ENOENT"===g.code)return log.verbose("Generator.init()._checkoutLibs()",a.locate+" does not exist."),
log.verbose("Generator.init()._checkoutLibs()","git shallow clone "+a.url+" # branch: "+a.target),git.shallowClone(a.url,a.locate,a.target);throw g;}})).then(function(a){log.verbose("Generator.init()._checkoutLibs() done.")})["catch"](function(a){log.verbose("Generator.init()._checkoutLibs()#err:",a);throw a;})}var d,a=path.resolve(f.out),l=path.join(a,".enyoconfig");log.verbose("Generator.init()","options:"+f);try{if(d=fs.statSync(a),!d.isDirectory())throw Error(a+" is not a directory.");}catch(b){if(b&&
"ENOENT"===b.code)throw Error(a+" does not exist.");}return Promise.resolve().then(function(){return git.verifyGit({openUrl:!0})}).then(function(){try{var b;fs.accessSync(l,fs.F_OK);b=readJsonSync(l);console.log("Initializing as described in "+l);return k(b,a)}catch(p){throw p&&"ENOENT"===p.code&&(p=Error(l+" does not exist.")),p;}}).then(function(){log.verbose("Generator.init() done");return{msg:"Success"}})["catch"](function(a){log.verbose("Generator.init() err:",a);throw a;})};module.exports=Generator;
